# Generated by Django 5.2.7 on 2025-10-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='avatar',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
