# Generated by Django 5.2.7 on 2025-10-25 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_attempt_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rounds/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='quiz.quiz')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='round',
            field=models.ForeignKey(blank=True, help_text='Optional: assign this question to a round.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quiz.round'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('quiz', 'name'), name='uniq_round_name_per_quiz'),
        ),
    ]
