# Generated by Django 5.2.7 on 2025-12-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_round_question_round_round_uniq_round_name_per_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Custom answer time in seconds for this question. Leave blank to use the quiz default.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='reveal_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Custom reveal time in seconds for this question. Leave blank to use the quiz default.', null=True),
        ),
    ]
