# Generated by Django 5.2.7 on 2025-12-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_answer_seconds_question_reveal_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='pause_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Pause after this round (in seconds) before the next question starts. Leave blank or 0 for no pause.', null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='phase',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('ANSWER', 'Answering'), ('REVEAL', 'Reveal'), ('ROUND_BREAK', 'Round break'), ('FINISHED', 'Finished')], default='WAITING', max_length=20),
        ),
    ]
