# Generated by Django 5.2.7 on 2025-12-09 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_round_pause_seconds_alter_quiz_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_special_icon',
            field=models.BooleanField(default=False, help_text='Show a clickable special prize icon on this question.'),
        ),
        migrations.AddField(
            model_name='question',
            name='special_icon',
            field=models.CharField(blank=True, help_text='Emoji or short text to use for the special icon (if enabled).', max_length=32),
        ),
        migrations.CreateModel(
            name='SpecialClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_clicks', to='quiz.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_clicks', to='quiz.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_clicks', to='quiz.quiz')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
